name: main.yml
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/docker:development-target
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y pylint flake8
      - name: Run Pylint
        run: |
          pylint ./sbaid
      - name: Run flake
        run: |
          flake8 ./sbaid