permissions:
  contents: read
name: ci
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/leolost2605/docker:ubuntu-pygobject
    steps:
      - uses: actions/checkout@v4
      # Deps should for speed reasons be added to the docker file and not installed here
      - name: Run Pylint (Naming and PEP 8 style)
        run: |
          /venv/bin/pylint ./sbaid
      - name: Run flake (Formatting)
        run: |
          /venv/bin/flake8 ./sbaid
      - name: Run mypy (Type checking)
        run: |
          /venv/bin/mypy --strict ./sbaid

  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/leolost2605/docker:ubuntu-pygobject
    steps:
      - uses: actions/checkout@v4
      # Deps should for speed reasons be added to the docker file and not installed here
      - name: Run tests
        run: |
          /venv/bin/python -m unittest -v
