permissions:
  contents: read
name: ci
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/leolost2605/docker:ubuntu-pygobject
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          python3 -m venv ~/venv
          ~/venv/bin/pip install pygobject-stubs pylint flake8 mypy pycairo PyGObject
      - name: Run Pylint (Naming and PEP 8 style)
        run: |
          ~/venv/bin/pylint ./sbaid
      - name: Run flake (Formatting)
        run: |
          ~/venv/bin/flake8 ./sbaid
      - name: Run mypy (Type checking)
        run: |
          ~/venv/bin/mypy --strict ./sbaid

  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/leolost2605/docker:ubuntu-pygobject
    steps:
      - uses: actions/checkout@v4
      # We don't install our own dependencies because our image comes already with them
      - name: Run tests
        run: |
          ~/venv/bin/python -m unittest -v
