name: main.yml
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/docker:development-target
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y python3-full pip gir1.2-girepository-2.0
          python3 -m venv ~/venv
          ~/venv/bin/pip install pygobject-stubs pylint flake8 mypy PyGObject
      - name: Run Pylint (Naming and PEP 8 style)
        run: |
          ~/venv/bin/pylint --disable too-few-public-methods ./sbaid
      - name: Run flake (Formatting)
        run: |
          ~/venv/bin/flake8 ./sbaid
      - name: Run mypy (Type checking)
        run: |
          ~/venv/bin/mypy --strict ./sbaid
