name: main.yml
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/docker:development-target
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y pylint flake8 mypy
      - name: Run Pylint (Naming and PEP 8 style)
        run: |
          pylint --disable too-few-public-methods ./sbaid
      - name: Run flake (Formatting)
        run: |
          flake8 ./sbaid
      - name: Run mypy (Type checking)
        run: |
          mypy --strict ./sbaid
