name: main.yml
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/docker:8
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y pip
          pip install flake8 pylint
      - name: Run Lint
        run: |
          pylint ./sbaid
          flake8 ./sbaid